// cankao/pages/Home.tsx
import { Link } from "react-router-dom";
import { motion } from "motion/react";
import { Users, Zap, Gamepad, Palette, ArrowRight, Download, Play } from "lucide-react";

export function Home() {
  return (
    <div className="flex flex-col gap-16 pb-16">
      {/* Hero Section */}
      <section className="relative h-[80vh] flex items-center justify-center overflow-hidden">
        {/* Dynamic Background Placeholder */}
        <div className="absolute inset-0 z-0">
          <div className="absolute inset-0 bg-gradient-to-b from-background/40 via-background/60 to-background z-10" />
          <img 
            src="https://picsum.photos/seed/pixelart/1920/1080?blur=2" 
            alt="Game Background" 
            className="w-full h-full object-cover opacity-50"
            referrerPolicy="no-referrer"
          />
        </div>

        <div className="relative z-20 text-center px-4 max-w-4xl mx-auto">
          <motion.h1 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5 }}
            className="text-6xl md:text-8xl font-black tracking-tighter mb-6 text-transparent bg-clip-text bg-gradient-to-r from-primary to-accent"
          >
            VerseBrawl
          </motion.h1>
          <motion.p 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.1 }}
            className="text-xl md:text-3xl font-medium text-foreground/90 mb-10"
          >
            2D 像素对战，指尖巅峰对决
          </motion.p>
          <motion.div 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.2 }}
            className="flex flex-col sm:flex-row items-center justify-center gap-6"
          >
            <Link 
              to="/download" 
              className="flex items-center gap-2 bg-primary text-primary-foreground px-10 py-5 rounded-xl font-black text-xl uppercase tracking-wider border-b-4 border-orange-900 hover:bg-primary/90 hover:translate-y-[2px] hover:border-b-2 active:translate-y-[4px] active:border-b-0 transition-all"
            >
              <Download className="w-6 h-6" />
              立即下载
            </Link>
            <Link 
              to="/download" 
              className="flex items-center gap-2 bg-secondary text-secondary-foreground px-10 py-5 rounded-xl font-black text-xl uppercase tracking-wider border-b-4 border-black hover:bg-muted hover:translate-y-[2px] hover:border-b-2 active:translate-y-[4px] active:border-b-0 transition-all"
            >
              <Play className="w-6 h-6" />
              在线试玩
            </Link>
          </motion.div>
        </div>
      </section>

      {/* Core Features */}
      <section className="container mx-auto px-4">
        <div className="text-center mb-12">
          <h2 className="text-3xl md:text-4xl font-bold mb-4">核心亮点</h2>
          <p className="text-muted-foreground">体验前所未有的像素格斗快感</p>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
          {[
            { icon: Users, title: "多人对战", desc: "支持全球玩家实时匹配，体验酣畅淋漓的竞技对决。" },
            { icon: Zap, title: "丰富技能", desc: "每个角色拥有独特的技能树，自由组合打出华丽连招。" },
            { icon: Gamepad, title: "简洁操作", desc: "易于上手的操作逻辑，硬核的判定机制，兼顾新手与高玩。" },
            { icon: Palette, title: "自定义角色", desc: "海量外观配件，打造属于你独一无二的专属格斗家。" },
          ].map((feature, i) => (
            <motion.div 
              key={i}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: i * 0.1 }}
              className="bg-card border border-border rounded-2xl p-6 hover:border-primary/50 transition-colors group"
            >
              <div className="w-12 h-12 bg-primary/10 rounded-xl flex items-center justify-center mb-4 group-hover:bg-primary/20 transition-colors">
                <feature.icon className="w-6 h-6 text-primary" />
              </div>
              <h3 className="text-xl font-bold mb-2">{feature.title}</h3>
              <p className="text-muted-foreground text-sm leading-relaxed">{feature.desc}</p>
            </motion.div>
          ))}
        </div>
      </section>

      {/* Latest News & Screenshots */}
      <section className="container mx-auto px-4 grid grid-cols-1 lg:grid-cols-3 gap-8">
        {/* News */}
        <div className="lg:col-span-1 flex flex-col gap-6">
          <div className="flex items-center justify-between">
            <h2 className="text-2xl font-bold">最新动态</h2>
            <Link to="/announcements" className="text-sm text-primary hover:underline flex items-center gap-1">
              更多 <ArrowRight className="w-4 h-4" />
            </Link>
          </div>
          <div className="flex flex-col gap-4">
            {[
              { title: "v1.2.0 版本更新：全新冰雪地图上线！", date: "2026-04-08", tag: "版本更新" },
              { title: "周末双倍积分活动开启", date: "2026-04-05", tag: "活动" },
            ].map((news, i) => (
              <Link key={i} to="/announcements" className="group bg-card border border-border rounded-xl p-4 hover:border-primary/50 transition-colors">
                <div className="flex items-center gap-2 mb-2">
                  <span className="text-xs font-medium px-2 py-1 bg-primary/10 text-primary rounded-md">{news.tag}</span>
                  <span className="text-xs text-muted-foreground">{news.date}</span>
                </div>
                <h3 className="font-medium group-hover:text-primary transition-colors line-clamp-2">{news.title}</h3>
              </Link>
            ))}
          </div>
        </div>

        {/* Screenshots */}
        <div className="lg:col-span-2 flex flex-col gap-6">
          <h2 className="text-2xl font-bold">游戏截图</h2>
          <div className="grid grid-cols-2 gap-4">
            <img src="https://picsum.photos/seed/game1/800/450" alt="Screenshot 1" className="rounded-xl border border-border w-full aspect-video object-cover hover:opacity-80 transition-opacity cursor-pointer" referrerPolicy="no-referrer" />
            <img src="https://picsum.photos/seed/game2/800/450" alt="Screenshot 2" className="rounded-xl border border-border w-full aspect-video object-cover hover:opacity-80 transition-opacity cursor-pointer" referrerPolicy="no-referrer" />
          </div>
        </div>
      </section>
    </div>
  );
}

// src/views/Home.vue
<template>
  <div class="home">
    <section class="hero">
      <div class="hero-bg">
        <div class="hero-bg-gradient"></div>
      </div>
      <div class="hero-content">
        <h1 class="hero-title">{{ gameInfo?.gameName || 'VerseBrawl' }}</h1>
        <p class="hero-tagline">{{ gameInfo?.slogan || '2D 像素对战，指尖巅峰对决' }}</p>
        <div class="hero-actions">
          <router-link to="/download" class="btn btn-primary">
            <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
              <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/>
              <polyline points="7 10 12 15 17 10"/>
              <line x1="12" y1="15" x2="12" y2="3"/>
            </svg>
            立即下载
          </router-link>
          <router-link to="/download" class="btn btn-secondary">
            <svg width="20" height="20" viewBox="0 0 24 24" fill="currentColor">
              <polygon points="5 3 19 12 5 21 5 3"/>
            </svg>
            在线试玩
          </router-link>
        </div>
      </div>
    </section>

    <section class="features container">
      <div class="features-header">
        <h2 class="section-title">核心亮点</h2>
        <p class="section-desc">体验前所未有的像素格斗快感</p>
      </div>
      <div class="features-grid">
        <div class="feature-card" v-for="(feature, i) in features" :key="i">
          <div class="feature-icon">
            <component :is="feature.icon" />
          </div>
          <h3 class="feature-title">{{ feature.title }}</h3>
          <p class="feature-desc">{{ feature.desc }}</p>
        </div>
      </div>
    </section>

    <section class="news-section container">
      <div class="news-column">
        <div class="column-header">
          <h2 class="column-title">最新动态</h2>
          <router-link to="/notice" class="view-more">
            更多
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
              <line x1="5" y1="12" x2="19" y2="12"/>
              <polyline points="12 5 19 12 12 19"/>
            </svg>
          </router-link>
        </div>
        <div class="news-list">
          <div 
            class="news-card" 
            v-for="notice in notices.slice(0, 2)" 
            :key="notice.id" 
            @click="$router.push(`/notice/${notice.id}`)"
          >
            <div class="news-meta">
              <span class="news-badge" :class="getCategoryClass(notice.category)">{{ notice.category }}</span>
              <span class="news-date">{{ formatTime(notice.createTime) }}</span>
            </div>
            <h3 class="news-title">{{ notice.title }}</h3>
          </div>
        </div>
      </div>
      
      <div class="screenshots-column">
        <h2 class="column-title">游戏截图</h2>
        <div class="screenshots-grid">
          <div class="screenshot-placeholder">
            <div class="screenshot-inner">
              <svg width="48" height="48" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1">
                <rect x="3" y="3" width="18" height="18" rx="2" ry="2"/>
                <circle cx="8.5" cy="8.5" r="1.5"/>
                <polyline points="21 15 16 10 5 21"/>
              </svg>
            </div>
          </div>
          <div class="screenshot-placeholder">
            <div class="screenshot-inner">
              <svg width="48" height="48" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1">
                <rect x="3" y="3" width="18" height="18" rx="2" ry="2"/>
                <circle cx="8.5" cy="8.5" r="1.5"/>
                <polyline points="21 15 16 10 5 21"/>
              </svg>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
</template>

<script setup>
import { ref, onMounted, h } from 'vue'
import { getHomeData } from '../utils/api'

const gameInfo = ref(null)
const notices = ref([])
const serverStatus = ref('online')

const UsersIcon = {
  render() {
    return h('svg', { width: 24, height: 24, viewBox: '0 0 24 24', fill: 'none', stroke: 'currentColor', 'stroke-width': 2 }, [
      h('path', { d: 'M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2' }),
      h('circle', { cx: 9, cy: 7, r: 4 }),
      h('path', { d: 'M23 21v-2a4 4 0 0 0-3-3.87' }),
      h('path', { d: 'M16 3.13a4 4 0 0 1 0 7.75' })
    ])
  }
}

const ZapIcon = {
  render() {
    return h('svg', { width: 24, height: 24, viewBox: '0 0 24 24', fill: 'none', stroke: 'currentColor', 'stroke-width': 2 }, [
      h('polygon', { points: '13 2 3 14 12 14 11 22 21 10 12 10 13 2' })
    ])
  }
}

const GamepadIcon = {
  render() {
    return h('svg', { width: 24, height: 24, viewBox: '0 0 24 24', fill: 'none', stroke: 'currentColor', 'stroke-width': 2 }, [
      h('rect', { x: 2, y: 6, width: 20, height: 12, rx: 2 }),
      h('circle', { cx: 8, cy: 12, r: 2 }),
      h('circle', { cx: 16, cy: 12, r: 2 })
    ])
  }
}

const PaletteIcon = {
  render() {
    return h('svg', { width: 24, height: 24, viewBox: '0 0 24 24', fill: 'none', stroke: 'currentColor', 'stroke-width': 2 }, [
      h('circle', { cx: 12, cy: 12, r: 10 }),
      h('circle', { cx: 12, cy: 8, r: 2, fill: 'currentColor' }),
      h('circle', { cx: 8, cy: 14, r: 2, fill: 'currentColor' }),
      h('circle', { cx: 16, cy: 14, r: 2, fill: 'currentColor' })
    ])
  }
}

const features = [
  { icon: UsersIcon, title: '多人对战', desc: '支持全球玩家实时匹配，体验酣畅淋漓的竞技对决。' },
  { icon: ZapIcon, title: '丰富技能', desc: '每个角色拥有独特的技能树，自由组合打出华丽连招。' },
  { icon: GamepadIcon, title: '简洁操作', desc: '易于上手的操作逻辑，硬核的判定机制，兼顾新手与高玩。' },
  { icon: PaletteIcon, title: '自定义角色', desc: '海量外观配件，打造属于你独一无二的专属格斗家。' }
]

const formatTime = (time) => {
  if (!time) return ''
  return new Date(time).toLocaleDateString('zh-CN')
}

const getCategoryClass = (category) => {
  return {
    'badge-update': category === '版本更新',
    'badge-event': category === '活动通知',
    'badge-maintenance': category === '维护公告'
  }
}

onMounted(async () => {
  try {
    const res = await getHomeData()
    gameInfo.value = res.data.gameInfo
    notices.value = res.data.latestNotices
    serverStatus.value = res.data.serverStatus
  } catch (e) {
    console.error(e)
  }
})
</script>

<style scoped>
.home {
  display: flex;
  flex-direction: column;
  gap: 4rem;
  padding-bottom: 4rem;
}

.hero {
  position: relative;
  min-height: 80vh;
  display: flex;
  align-items: center;
  justify-content: center;
  overflow: hidden;
}

.hero-bg {
  position: absolute;
  inset: 0;
  z-index: 0;
}

.hero-bg-gradient {
  position: absolute;
  inset: 0;
  background: linear-gradient(to bottom, rgba(26, 17, 14, 0.4) 0%, rgba(26, 17, 14, 0.6) 50%, var(--color-background) 100%);
  z-index: 10;
}

.hero-content {
  position: relative;
  z-index: 20;
  text-align: center;
  padding: 0 1rem;
  max-width: 64rem;
  margin: 0 auto;
}

.hero-title {
  font-size: 4rem;
  font-weight: 900;
  letter-spacing: -0.02em;
  margin-bottom: 1.5rem;
  background: linear-gradient(to right, var(--color-primary), var(--color-accent));
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  background-clip: text;
}

.hero-tagline {
  font-size: 1.5rem;
  font-weight: 500;
  color: var(--color-foreground);
  opacity: 0.9;
  margin-bottom: 2.5rem;
}

.hero-actions {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 1.5rem;
}

@media (min-width: 640px) {
  .hero-actions {
    flex-direction: row;
    justify-content: center;
  }
}

.features {
  padding-top: 0;
}

.features-header {
  text-align: center;
  margin-bottom: 3rem;
}

.section-desc {
  color: var(--color-muted-foreground);
  font-size: 1.125rem;
}

.features-grid {
  display: grid;
  grid-template-columns: 1fr;
  gap: 1.5rem;
}

@media (min-width: 768px) {
  .features-grid {
    grid-template-columns: repeat(2, 1fr);
  }
}

@media (min-width: 1024px) {
  .features-grid {
    grid-template-columns: repeat(4, 1fr);
  }
}

.feature-card {
  background: var(--color-card);
  border: 1px solid var(--color-border);
  border-radius: var(--radius-2xl);
  padding: 1.5rem;
  transition: border-color 0.2s ease;
}

.feature-card:hover {
  border-color: rgba(255, 85, 0, 0.5);
}

.feature-icon {
  width: 3rem;
  height: 3rem;
  background: rgba(255, 85, 0, 0.1);
  border-radius: var(--radius-xl);
  display: flex;
  align-items: center;
  justify-content: center;
  margin-bottom: 1rem;
  color: var(--color-primary);
}

.feature-title {
  font-size: 1.25rem;
  font-weight: 700;
  margin-bottom: 0.5rem;
}

.feature-desc {
  font-size: 0.875rem;
  line-height: 1.5;
  color: var(--color-muted-foreground);
}

.news-section {
  display: grid;
  grid-template-columns: 1fr;
  gap: 2rem;
}

@media (min-width: 1024px) {
  .news-section {
    grid-template-columns: 1fr 2fr;
  }
}

.news-column {
  display: flex;
  flex-direction: column;
  gap: 1.5rem;
}

.column-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
}

.column-title {
  font-size: 1.5rem;
  font-weight: 700;
}

.view-more {
  display: flex;
  align-items: center;
  gap: 0.25rem;
  font-size: 0.875rem;
  color: var(--color-primary);
}

.view-more:hover {
  text-decoration: underline;
}

.news-list {
  display: flex;
  flex-direction: column;
  gap: 1rem;
}

.news-card {
  background: var(--color-card);
  border: 1px solid var(--color-border);
  border-radius: var(--radius-xl);
  padding: 1rem;
  cursor: pointer;
  transition: border-color 0.2s ease;
}

.news-card:hover {
  border-color: rgba(255, 85, 0, 0.5);
}

.news-meta {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  margin-bottom: 0.5rem;
}

.news-badge {
  font-size: 0.75rem;
  font-weight: 600;
  padding: 0.25rem 0.5rem;
  border-radius: var(--radius-md);
  background: rgba(255, 85, 0, 0.1);
  color: var(--color-primary);
}

.news-badge.badge-update {
  background: rgba(255, 85, 0, 0.1);
  color: var(--color-primary);
}

.news-badge.badge-event {
  background: rgba(255, 170, 0, 0.1);
  color: var(--color-accent);
}

.news-badge.badge-maintenance {
  background: rgba(163, 144, 136, 0.1);
  color: var(--color-muted-foreground);
}

.news-date {
  font-size: 0.75rem;
  color: var(--color-muted-foreground);
}

.news-title {
  font-size: 1rem;
  font-weight: 500;
  color: var(--color-foreground);
  transition: color 0.2s ease;
}

.news-card:hover .news-title {
  color: var(--color-primary);
}

.screenshots-column {
  display: flex;
  flex-direction: column;
  gap: 1.5rem;
}

.screenshots-grid {
  display: grid;
  grid-template-columns: repeat(2, 1fr);
  gap: 1rem;
}

.screenshot-placeholder {
  aspect-ratio: 16/9;
  background: var(--color-card);
  border: 1px solid var(--color-border);
  border-radius: var(--radius-xl);
  display: flex;
  align-items: center;
  justify-content: center;
  cursor: pointer;
  transition: opacity 0.2s ease;
}

.screenshot-placeholder:hover {
  opacity: 0.8;
}

.screenshot-inner {
  color: var(--color-muted-foreground);
}

@media (max-width: 768px) {
  .hero-title {
    font-size: 2.5rem;
  }
  
  .hero-tagline {
    font-size: 1.125rem;
  }
}
</style>
